const apiPath = {
  BANNERS: "/api/QuanLyPhim/LayDanhSachBanner",
  MOVIES: "/api/QuanLyPhim/LayDanhSachPhimPhanTrang",
  MOVIES_DETAIL: "/api/QuanLyPhim/LayThongTinPhim",
  MOVIES_DETAIL_SCHEDULE: "/api/QuanLyRap/LayThongTinLichChieuPhim",
  CINEMAS: "/api/QuanLyRap/LayThongTinHeThongRap",
  SCHEDULE_CINEMAS: "/api/QuanLyRap/LayThongTinLichChieuHeThongRap",
  USER: "/api/QuanLyNguoiDung/DangNhap",
  USER_INFOR: "/api/QuanLyNguoiDung/ThongTinTaiKhoan",
  USER_ACCOUNT: "/api/QuanLyNguoiDung/ThemNguoiDung",
  USER_EDIT: "/api/QuanLyNguoiDung/CapNhatThongTinNguoiDung",
  USER_DELETE: "/api/QuanLyNguoiDung/XoaNguoiDung",
  USER_LIST: "/api/QuanLyNguoiDung/LayDanhSachNguoiDungPhanTrang",
  USER_SEARCH:"/api/QuanLyNguoiDung/TimKiemNguoiDung",
  BOOK_TICKET_LIST: "/api/QuanLyDatVe/LayDanhSachPhongVe",
  BOOK_TICKET: "/api/QuanLyDatVe/DatVe",
  SIGNUP: "/api/QuanLyNguoiDung/DangKy",
  ADMIN: "/api/QuanLyPhim/LayDanhSachPhimPhanTrang",
  ADMIN_SEARCH: "/api/QuanLyPhim/LayDanhSachPhim",
  UP_HINH: "/api/QuanLyPhim/ThemPhimUploadHinh",
  EDIT_HINH: "/api/QuanLyPhim/CapNhatPhimUpload",
  DELETE_HINH: "/api/QuanLyPhim/XoaPhim",
  CLUSTER_CINEMAS: "/api/QuanLyRap/LayThongTinCumRapTheoHeThong",
  CREATE_SHOWTIMES: "/api/QuanLyDatVe/TaoLichChieu",
};

export default apiPath;
